version: '3.8'

services:
  mcr-api:
    build:
      context: .
      target: builder
    ports:
      - '8080:8080'
    environment:
      DEVELOPMENT: 'true'
    volumes:
      - ./build:/app/build
    command: [ "./gradlew", "run" ]
  builder:
    build:
      context: .
      target: builder
    volumes:
      - ./build:/app/build
      - ./src:/app/src
    command: [ "./gradlew", "-t", "build" ]
