name: Build docker image for release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Use build caches
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.ref }}-buildx-${{ github.sha }}
          restore-keys: |
            - refs/head/main
      - name: Extract tag name
        shell: bash
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
        id: extract_tag
      - name: Make docker image tags
        env:
          TAG_NAME: ${{ steps.extract_tag.outputs.tag }}
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/mcr-api-server
          FULL_TAG=${IMAGE}:${TAG_NAME}
          LATEST_TAG=${IMAGE}:latest
          echo "TAGS=${FULL_TAG},${LATEST_TAG}" >> ${GITHUB_ENV}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            GRADLE_OPTS="-Djdk.lang.Process.launchMechanism=vfork"
          tags: ${{ env.TAGS }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
